doctrine:
    dbal:
        driver: 'pdo_pgsql'
        host: '127.0.0.1'
        port: 5432
        dbname: 'adopt'
        user: 'user'
        password: 'pass'
        charset: 'utf8'
        server_version: '16'
        types:
          geometry: CrEOF\Spatial\DBAL\Types\GeometryType
          point: CrEOF\Spatial\DBAL\Types\Geometry\PointType
          polygon: CrEOF\Spatial\DBAL\Types\Geometry\PolygonType
          linestring: CrEOF\Spatial\DBAL\Types\Geometry\LineStringType
          geography: CrEOF\Spatial\DBAL\Types\GeographyType
        mapping_types:
          geography: geography

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.default
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
        dql:
          numeric_functions:
            ST_Distance: CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STDistance
            ST_DWithin: CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STDWithin
          string_functions:
            ST_AsText: CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STAsText
            ST_GeogFromText: CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STGeogFromText
            ST_MakePoint: CrEOF\Spatial\ORM\Query\AST\Functions\PostgreSql\STMakePoint