version: '3.8'

services:
  ###> doctrine/doctrine-bundle ###
  database:
    container_name: db
    image: bitnami/postgresql:16.1.0
    ports:
      - "5432:5432"
    environment:
      POSTGRESQL_DATABASE: adopt
      POSTGRESQL_PASSWORD: pass
      POSTGRESQL_USER: user
  ###< doctrine/doctrine-bundle ###