version: '3.8'

networks:
  app_network:

services:
  ###> doctrine/doctrine-bundle ###
  database:
    container_name: database
    image: postgis/postgis:16-3.4
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: adopt
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: user
      POSTGRESQL_POSTGRES_PASSWORD: postpass
    networks:
      - app_network

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
  ###< doctrine/doctrine-bundle ###
