version: '3.8'

networks:
  app_network:

services:
  ###> doctrine/doctrine-bundle ###
  database:
    container_name: db
    image: bitnami/postgresql:16.1.0
    ports:
      - "5432:5432"
    environment:
      POSTGRESQL_DATABASE: adopt
      POSTGRESQL_PASSWORD: pass
      POSTGRESQL_USER: user
      POSTGRESQL_POSTGRES_PASSWORD: postpass
    networks:
      - app_network

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
  ###< doctrine/doctrine-bundle ###
