<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260515103010 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE EXTENSION IF NOT EXISTS postgis');
        $this->addSql('CREATE TABLE AdoptionRequest (status VARCHAR(255) NOT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, description TEXT DEFAULT NULL, createdAt TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updatedAt TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT DEFAULT NULL, animal_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_709FB695A76ED395 ON AdoptionRequest (user_id)');
        $this->addSql('CREATE INDEX IDX_709FB6958E962C16 ON AdoptionRequest (animal_id)');
        $this->addSql('CREATE TABLE Animal (name VARCHAR(255) NOT NULL, sex VARCHAR(255) NOT NULL, birthDate TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, images JSON DEFAULT NULL, weight DOUBLE PRECISION DEFAULT NULL, fur VARCHAR(255) DEFAULT NULL, color VARCHAR(255) DEFAULT NULL, vaccination BOOLEAN DEFAULT NULL, sterilized BOOLEAN NOT NULL, dewormed BOOLEAN NOT NULL, price DOUBLE PRECISION DEFAULT NULL, geo GEOGRAPHY(POINT,4326), id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, description TEXT DEFAULT NULL, status VARCHAR(255) NOT NULL, dogsAffinities VARCHAR(255) DEFAULT NULL, catsAffinities VARCHAR(255) DEFAULT NULL, childAffinities VARCHAR(255) DEFAULT NULL, createdAt TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updatedAt TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, address_line1 VARCHAR(255) DEFAULT NULL, address_line2 VARCHAR(255) DEFAULT NULL, address_postalCode VARCHAR(32) DEFAULT NULL, address_city VARCHAR(150) DEFAULT NULL, address_country VARCHAR(2) DEFAULT \'FR\', geo_lat DOUBLE PRECISION DEFAULT NULL, geo_lng DOUBLE PRECISION DEFAULT NULL, organisation_id INT DEFAULT NULL, manager_id INT DEFAULT NULL, species VARCHAR(255) NOT NULL, size VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6D0726299E6B1585 ON Animal (organisation_id)');
        $this->addSql('CREATE INDEX IDX_6D072629783E3463 ON Animal (manager_id)');
        $this->addSql('CREATE TABLE Comment (content TEXT NOT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, createdAt TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updatedAt TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, adoptionRequest_id INT NOT NULL, author_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5BC96BF012F08080 ON Comment (adoptionRequest_id)');
        $this->addSql('CREATE INDEX IDX_5BC96BF0F675F31B ON Comment (author_id)');
        $this->addSql('CREATE TABLE Organisation (name VARCHAR(255) NOT NULL, logo VARCHAR(255) DEFAULT NULL, color VARCHAR(255) DEFAULT NULL, images JSON DEFAULT NULL, signature TEXT DEFAULT NULL, geo GEOGRAPHY(POINT,4326), id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, description TEXT DEFAULT NULL, createdAt TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updatedAt TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, address_line1 VARCHAR(255) DEFAULT NULL, address_line2 VARCHAR(255) DEFAULT NULL, address_postalCode VARCHAR(32) DEFAULT NULL, address_city VARCHAR(150) DEFAULT NULL, address_country VARCHAR(2) DEFAULT \'FR\', geo_lat DOUBLE PRECISION DEFAULT NULL, geo_lng DOUBLE PRECISION DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE "user" (email VARCHAR(180) NOT NULL, name VARCHAR(255) NOT NULL, firstName VARCHAR(255) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, isVerified BOOLEAN NOT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, createdAt TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updatedAt TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, organisation_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649E7927C74 ON "user" (email)');
        $this->addSql('CREATE INDEX IDX_8D93D6499E6B1585 ON "user" (organisation_id)');
        $this->addSql('ALTER TABLE AdoptionRequest ADD CONSTRAINT FK_709FB695A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE AdoptionRequest ADD CONSTRAINT FK_709FB6958E962C16 FOREIGN KEY (animal_id) REFERENCES Animal (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE Animal ADD CONSTRAINT FK_6D0726299E6B1585 FOREIGN KEY (organisation_id) REFERENCES Organisation (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE Animal ADD CONSTRAINT FK_6D072629783E3463 FOREIGN KEY (manager_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE Comment ADD CONSTRAINT FK_5BC96BF012F08080 FOREIGN KEY (adoptionRequest_id) REFERENCES AdoptionRequest (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE Comment ADD CONSTRAINT FK_5BC96BF0F675F31B FOREIGN KEY (author_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "user" ADD CONSTRAINT FK_8D93D6499E6B1585 FOREIGN KEY (organisation_id) REFERENCES Organisation (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE AdoptionRequest DROP CONSTRAINT FK_709FB695A76ED395');
        $this->addSql('ALTER TABLE AdoptionRequest DROP CONSTRAINT FK_709FB6958E962C16');
        $this->addSql('ALTER TABLE Animal DROP CONSTRAINT FK_6D0726299E6B1585');
        $this->addSql('ALTER TABLE Animal DROP CONSTRAINT FK_6D072629783E3463');
        $this->addSql('ALTER TABLE Comment DROP CONSTRAINT FK_5BC96BF012F08080');
        $this->addSql('ALTER TABLE Comment DROP CONSTRAINT FK_5BC96BF0F675F31B');
        $this->addSql('ALTER TABLE "user" DROP CONSTRAINT FK_8D93D6499E6B1585');
        $this->addSql('DROP TABLE AdoptionRequest');
        $this->addSql('DROP TABLE Animal');
        $this->addSql('DROP TABLE Comment');
        $this->addSql('DROP TABLE Organisation');
        $this->addSql('DROP TABLE "user"');
    }
}
